#! /usr/bin/env python
import sys

from expediacrawler import offersFinder

orig_city = sys.argv[1]
dest_city = sys.argv[2]
leave = sys.argv[3]
back = sys.argv[4]
flex = 0
if len(sys.argv) == 6:
    flex = int(sys.argv[5])
offersFinder.get_offers(orig_city=orig_city, dest_city=dest_city, leave=leave, back=back, forward_days=flex)
